apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: urlshortner-ingress
spec:
  rules:
    - host: urlshortner.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: urlshortner-backend
                port:
                  number: 8080
